# Generated by Django 5.1.3 on 2024-11-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
                ('faculty', models.IntegerField()),
                ('details', models.CharField(max_length=30)),
            ],
        ),
    ]
